# Generated by Django 5.1.3 on 2024-12-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('sigla', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_estabelecimento', models.CharField(max_length=100)),
                ('razao_social', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=100)),
                ('idioma', models.CharField(max_length=50)),
                ('situacao_cadastral', models.CharField(max_length=100)),
                ('data_situacao_cadastral', models.DateField()),
                ('motivo_situacao_cadastral', models.TextField(blank=True, null=True)),
                ('situacao_especial', models.CharField(blank=True, max_length=100, null=True)),
                ('data_situacao_especial', models.DateField(blank=True, null=True)),
                ('optante_simples', models.BooleanField()),
                ('data_inicio_simples', models.DateField(blank=True, null=True)),
                ('data_fim_simples', models.DateField(blank=True, null=True)),
                ('optante_mei', models.BooleanField()),
                ('natureza_juridica', models.CharField(max_length=100)),
                ('categoria_administrativa', models.CharField(max_length=100)),
                ('porte', models.CharField(max_length=50)),
                ('setor_atividade', models.CharField(max_length=100)),
                ('capital_social', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_fundacao', models.DateField()),
                ('historico', models.TextField(blank=True, null=True)),
                ('ddd', models.CharField(max_length=2)),
                ('telefone1', models.CharField(blank=True, max_length=15, null=True)),
                ('ramal1', models.CharField(blank=True, max_length=10, null=True)),
                ('telefone2', models.CharField(blank=True, max_length=15, null=True)),
                ('ramal2', models.CharField(blank=True, max_length=10, null=True)),
                ('fax', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('cep', models.CharField(max_length=10)),
                ('tipo_cep', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco', models.CharField(max_length=255)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('socios', models.TextField(blank=True, help_text='Informe os sócios separados por vírgula ou de outra forma estruturada.', null=True)),
                ('representante_legal', models.CharField(blank=True, help_text='Nome do representante legal.', max_length=255, null=True)),
            ],
        ),
    ]
